In [11]:
import numpy as np;

#one dimension array
one_d_array = np.array([1,2,3,4,5])
print("one_d_array",one_d_array)

#shape
print("Shape",one_d_array.shape)
#ndim
print("ndim",one_d_array.ndim)
#dtype
print("dtype",one_d_array.dtype)
#size
print("size",one_d_array.size)

#two dimension array
two_d_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("two_d_array",two_d_array)

#shape
print("Shape",two_d_array.shape)
#ndim
print("ndim",two_d_array.ndim)
#dtype
print("dtype",two_d_array.dtype)
#size
print("size",two_d_array.size)


print(one_d_array+10)


one_d_array [1 2 3 4 5]
Shape (5,)
ndim 1
dtype int32
size 5
two_d_array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape (2, 5)
ndim 2
dtype int32
size 10
[11 12 13 14 15]


Why do we use NumPy in AI?

Numpy is faster because it store same data type in a continous block of memeory and perofrms operations useing optimized compiled code instead of looping though python objects one by one

In [15]:
#Indexing
arr = np.array([5,10,15,20,25,30,35,40])

#First element
print("First element",arr[0])

#Last element
print("Last element",arr[-1])

#First four elements
print("First four elements",arr[:4])

#Last three elements
print("Last three elements",arr[5:])

#Every second element
print("Every second element",])

#Reverse the array
print("Reverse the array",arr[::-1])

#Elements between 15 and 30 (inclusive)
print("Elements between 15 and 30 (inclusive)",arr[2:6])


First element 5
Last element 40
First four elements [ 5 10 15 20]
Last three elements [30 35 40]
Every second element []
Reverse the array [40 35 30 25 20 15 10  5]
Elements between 15 and 30 (inclusive) [15 20 25 30]


Why does arr[0:4] return 4 elements instead of 5?

Start is included, stop is excluded.  

What is the difference between arr[-1] and arr[:-1]?

arr[-1] returns the last value
arr[:-1] returns the all values except the last value

Square of every element.
Cube of every element.
Divide every element by 2.
Multiply every element by 100.
Find elements greater than 5.
Find elements less than or equal to 6.
Find elements that are even.

In [21]:
import numpy as np

arr = np.array([2,4,6,8,10])

square = arr ** 2
cube = arr ** 3
divide = arr/2
multiplyBy100 = arr * 100
greaterThanFive = arr>5
lessThanOrEqualToSix = arr<=6
evenNumbers = arr[arr%2 == 0]

print("square", square)
print("cube", cube)
print("divide", divide)
print("multiplyBy100", multiplyBy100)
print("greaterThanFive", greaterThanFive)
print("lessThanOrEqualToSix", lessThanOrEqualToSix)
print("evenNumbers", evenNumbers)


square [  4  16  36  64 100]
cube [   8   64  216  512 1000]
divide [1. 2. 3. 4. 5.]
multiplyBy100 [ 200  400  600  800 1000]
greaterThanFive [False False  True  True  True]
lessThanOrEqualToSix [ True  True  True False False]
evenNumbers [ 2  4  6  8 10]


Try these without using loops:

Find numbers greater than 15.
Find numbers between 10 and 25 (inclusive).
Replace all numbers greater than 20 with 100.
Find odd numbers.
Find numbers divisible by 5.
Calculate the sum of all elements.
Calculate the mean.
Calculate the maximum.
Calculate the minimum.
Calculate the standard deviation.

In [28]:
import numpy as np

arr = np.array([5,10,15,20,25,30])
one = arr[arr>15]
two = arr[(arr>10) & (arr<=25)]
three = arr.copy()
three[three>20] = 100
four = arr[arr%2!=0]
five = arr[arr%5 == 0]
six = np.sum(arr)
seven = np.mean(arr)
eight = np.max(arr)
nine = np.min(arr)
ten = np.std(arr)

print("one", one)
print("two", two)
print("three", three)
print("four", four)
print("five", five)
print("six", six)
print("seven", seven)
print("eight", eight)
print("nine", nine)
print("ten", ten)

one [20 25 30]
two [15 20 25]
three [  5  10  15  20 100 100]
four [ 5 15 25]
five [ 5 10 15 20 25 30]
six 105
seven 17.5
eight 30
nine 5
ten 8.539125638299666


Complete these tasks:

Print the shape.
Print the dimensions.
Print the size.
Print the first row.
Print the second column.
Print the last row.
Add 5 grace marks to every student.
Multiply all marks by 2.
Find the average mark of the entire matrix.
Find the maximum mark.
Find the minimum mark.

In [45]:
import numpy as np

marks = np.array([
    [85,90,88],
    [70,65,75],
    [95,92,98]
])

one = marks.shape
two = marks.ndim
three = marks.size
four = marks[0]
five = marks[:,1]
six = marks[2]
seven = marks+5
eight = marks*2
nine = marks.mean()
ten = np.max(marks)
eleven = np.min(marks)
arr = np.arange(1, 13)
print(arr)
print(one)
print(two)
print(three)
print(four)
print(five)
print(six)
print(seven)
print(eight)
print(nine)
print(ten)
print(eleven)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(3, 3)
2
9
[85 90 88]
[90 65 92]
[95 92 98]
[[ 90  95  93]
 [ 75  70  80]
 [100  97 103]]
[[170 180 176]
 [140 130 150]
 [190 184 196]]
84.22222222222223
98
65


Print the array.
Reshape it into 4 × 4.
Reshape it into 2 × 8.
Reshape it using -1.
Flatten the 4 × 4 matrix.
Transpose the 4 × 4 matrix.
Create a 3 × 3 zero matrix.
Create a 2 × 5 ones matrix.
Create a 4 × 4 identity matrix.
Generate numbers from 10 to 50 using arange().
Generate 6 evenly spaced numbers between 0 and 1 using linspace().
Generate 10 random integers between 1 and 100.

In [66]:
import numpy as np 

arr = np.arange(1,17)
reshape = arr.reshape(4,4)
reshape2 = arr.reshape(2,8)
reshape3 = arr.reshape(-1,8)
reshape4 = arr.reshape(2,-1)
zeroMatrix = np.zeros((3,3))
onesMatrix = np.ones((2,5))
identityMatrix = np.eye(4)
generateNum = np.arange(10,51)
linespace = np.linspace(0,1,6)
randomNum = np.random.randint(1,101,10)
print(arr)
print(reshape)
print(reshape2)
print(reshape3)
print(reshape4)
print(zeroMatrix)
print(onesMatrix)
print(identityMatrix)
print(generateNum)
print(linespace)
print(randomNum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[0.  0.2 0.4 0.6 0.8 1. ]
[95  9  1 74 20 15 94 67 42 33]


Create a copy of the array.
Create a view of the array.
Replace all values greater than 25 with 100 using where().
Check if any value is greater than 45.
Check if all values are greater than 5.
Remove duplicate values.
Sort the array.
Find the indexes that would sort the array.
Concatenate this array with:
b=np.array([60,70,80])
Vertically stack:
a=np.array([1,2,3])
b=np.array([4,5,6])
Horizontally stack the same arrays.
Split this array into two equal parts:
np.arange(1,11)

In [84]:
import numpy as np

arr = np.array([10,20,20,30,40,40,50])
copyOfArr = arr.copy()
viewOfArr = arr.view()
replaceNum = np.where(arr>25,100,0)
any_greater_45 = np.any(arr>45)
all_greater_5 = np.all(arr>5)
remove_duplicate = np.unique(arr)
sort_arr = np.sort(arr)
index_sort_arr = np.argsort(arr)
b=np.array([60,70,80])
add_arr = np.concatenate((arr,b))
a=np.array([1,2,3])
b=np.array([4,5,6])
vertically_stack = np.vstack((a,b))
horizontally_stack = np.hstack((a,b))
arr2 = np.arange(1,11)
split_arr = np.split(arr2,2)

print(arr)
print(copyOfArr)
print(viewOfArr)
print(replaceNum)
print(any_greater_45)
print(all_greater_5)
print(remove_duplicate)
print(sort_arr)
print(index_sort_arr)
print(add_arr)
print(vertically_stack)
print(horizontally_stack)
print(split_arr)

[10 20 20 30 40 40 50]
[10 20 20 30 40 40 50]
[10 20 20 30 40 40 50]
[  0   0   0 100 100 100 100]
True
True
[10 20 30 40 50]
[10 20 20 30 40 40 50]
[0 1 2 3 4 5 6]
[10 20 20 30 40 40 50 60 70 80]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
